### Домашнее задание

## Свойства матричных вычислений

In [1]:
import numpy as np

In [2]:
l = [[26, 18, 10, 18], [10, 13, 14, 12], [5, 13, 6, 11], [18, 16, 44, 10]]
A = np.array(l)
A

array([[26, 18, 10, 18],
       [10, 13, 14, 12],
       [ 5, 13,  6, 11],
       [18, 16, 44, 10]])

In [3]:
k = [[12, 18, 19, 14], [2, 4, 3, 12], [4, 5, 7, 74], [20, 21, 15, 42]]
B = np.array(k)
B

array([[12, 18, 19, 14],
       [ 2,  4,  3, 12],
       [ 4,  5,  7, 74],
       [20, 21, 15, 42]])

In [4]:
k = [[28, 14 , 17, 31], [4, 22, 11, 3], [17, 21, 15, 20], [17, 18, 0, 10]]
C = np.array(k)
C

array([[28, 14, 17, 31],
       [ 4, 22, 11,  3],
       [17, 21, 15, 20],
       [17, 18,  0, 10]])

Транспонирование матрицы:

In [5]:
A.transpose()

array([[26, 10,  5, 18],
       [18, 13, 13, 16],
       [10, 14,  6, 44],
       [18, 12, 11, 10]])

In [6]:
A.T

array([[26, 10,  5, 18],
       [18, 13, 13, 16],
       [10, 14,  6, 44],
       [18, 12, 11, 10]])

Дважды транспонированная матрица равна исходной матрице:

In [7]:
(A.T).T

array([[26, 18, 10, 18],
       [10, 13, 14, 12],
       [ 5, 13,  6, 11],
       [18, 16, 44, 10]])

Транспонирование суммы матриц равно сумме транспонированных матриц:

In [8]:
(A+B).T

array([[38, 12,  9, 38],
       [36, 17, 18, 37],
       [29, 17, 13, 59],
       [32, 24, 85, 52]])

In [9]:
A.T+B.T

array([[38, 12,  9, 38],
       [36, 17, 18, 37],
       [29, 17, 13, 59],
       [32, 24, 85, 52]])

Транспонирование произведения матриц равно произведению транспонированных
матриц расставленных в обратном порядке:

In [10]:
(A.dot(B)).T

array([[ 748,  442,  330,  624],
       [ 968,  554,  403,  818],
       [ 888,  507,  341,  848],
       [2076, 1836, 1132, 4120]])

In [11]:
(B.T).dot(A.T)

array([[ 748,  442,  330,  624],
       [ 968,  554,  403,  818],
       [ 888,  507,  341,  848],
       [2076, 1836, 1132, 4120]])

Транспонирование произведения матрицы на число равно произведению этого
числа на транспонированную матрицу:

In [12]:
t = 3

In [13]:
(t * A).T

array([[ 78,  30,  15,  54],
       [ 54,  39,  39,  48],
       [ 30,  42,  18, 132],
       [ 54,  36,  33,  30]])

In [14]:
t * (A.T)

array([[ 78,  30,  15,  54],
       [ 54,  39,  39,  48],
       [ 30,  42,  18, 132],
       [ 54,  36,  33,  30]])

Определители исходной и транспонированной матрицы совпадают:

In [15]:
format(np.linalg.det(A), '.9g')

'12272'

In [16]:
format(np.linalg.det(A.T), '.9g')

'12272'

Умножение матрицы на число


In [17]:
2 * A

array([[52, 36, 20, 36],
       [20, 26, 28, 24],
       [10, 26, 12, 22],
       [36, 32, 88, 20]])

Произведение единицы и любой заданной матрицы равно заданной матрице:

In [18]:
1 * A

array([[26, 18, 10, 18],
       [10, 13, 14, 12],
       [ 5, 13,  6, 11],
       [18, 16, 44, 10]])

Произведение нуля и любой матрицы равно нулевой матрице, размерность которой
равна исходной матрицы:

In [19]:
0 * A

array([[0, 0, 0, 0],
       [0, 0, 0, 0],
       [0, 0, 0, 0],
       [0, 0, 0, 0]])

 Произведение матрицы на сумму чисел равно сумме произведений матрицы на
каждое из этих чисел:

In [20]:
(2 + 3) * A

array([[130,  90,  50,  90],
       [ 50,  65,  70,  60],
       [ 25,  65,  30,  55],
       [ 90,  80, 220,  50]])

In [21]:
2 * A + 3 * A

array([[130,  90,  50,  90],
       [ 50,  65,  70,  60],
       [ 25,  65,  30,  55],
       [ 90,  80, 220,  50]])

Произведение матрицы на произведение двух чисел равно произведению второго
числа и заданной матрицы, умноженному на первое число:

In [22]:
(2 * 3) * A

array([[156, 108,  60, 108],
       [ 60,  78,  84,  72],
       [ 30,  78,  36,  66],
       [108,  96, 264,  60]])

In [23]:
2 * (3 * A)

array([[156, 108,  60, 108],
       [ 60,  78,  84,  72],
       [ 30,  78,  36,  66],
       [108,  96, 264,  60]])

Произведение суммы матриц на число равно сумме произведений этих матриц на
заданное число:

In [24]:
2 * (A + B)

array([[ 76,  72,  58,  64],
       [ 24,  34,  34,  48],
       [ 18,  36,  26, 170],
       [ 76,  74, 118, 104]])

In [25]:
2 * A + 2 * B

array([[ 76,  72,  58,  64],
       [ 24,  34,  34,  48],
       [ 18,  36,  26, 170],
       [ 76,  74, 118, 104]])

Сложение матриц


In [26]:
A + B

array([[38, 36, 29, 32],
       [12, 17, 17, 24],
       [ 9, 18, 13, 85],
       [38, 37, 59, 52]])

In [27]:
B + A

array([[38, 36, 29, 32],
       [12, 17, 17, 24],
       [ 9, 18, 13, 85],
       [38, 37, 59, 52]])

In [28]:
A + (B + C)

array([[ 66,  50,  46,  63],
       [ 16,  39,  28,  27],
       [ 26,  39,  28, 105],
       [ 55,  55,  59,  62]])

In [29]:
(A + B) + C

array([[ 66,  50,  46,  63],
       [ 16,  39,  28,  27],
       [ 26,  39,  28, 105],
       [ 55,  55,  59,  62]])

In [30]:
A + (-1)*A

array([[0, 0, 0, 0],
       [0, 0, 0, 0],
       [0, 0, 0, 0],
       [0, 0, 0, 0]])

Диаграмма матричного умножения


In [31]:
A.dot(B)

array([[ 748,  968,  888, 2076],
       [ 442,  554,  507, 1836],
       [ 330,  403,  341, 1132],
       [ 624,  818,  848, 4120]])

Ассоциативность умножения. Результат умножения матриц не зависит от порядка, в
котором будет выполняться эта операция:

In [32]:
A.dot(B.dot(C))

array([[ 75204,  87784,  36684,  64612],
       [ 54423,  62071,  21213,  43864],
       [ 35893,  41023,  15158,  29579],
       [105200, 118700,  32326,  79958]])

In [33]:
(A.dot(B)).dot(C)

array([[ 75204,  87784,  36684,  64612],
       [ 54423,  62071,  21213,  43864],
       [ 35893,  41023,  15158,  29579],
       [105200, 118700,  32326,  79958]])

Дистрибутивность умножения. Произведение матрицы на сумму матриц равно
сумме произведений матриц:

In [34]:
A.dot(B+C)

array([[2024, 2262, 1678, 3316],
       [1216, 1490, 1030, 2585],
       [ 811, 1083,  659, 1556],
       [2110, 2526, 1990, 5706]])

In [35]:
A.dot(B)+A.dot(C)

array([[2024, 2262, 1678, 3316],
       [1216, 1490, 1030, 2585],
       [ 811, 1083,  659, 1556],
       [2110, 2526, 1990, 5706]])

Умножение матриц в общем виде не коммутативно. Это означает, что для матриц не
выполняется правило независимости произведения от перестановки множителей:

In [36]:
A.dot(B)

array([[ 748,  968,  888, 2076],
       [ 442,  554,  507, 1836],
       [ 330,  403,  341, 1132],
       [ 624,  818,  848, 4120]])

In [37]:
B.dot(A)

array([[ 839,  921, 1102,  781],
       [ 323,  319,  622,  237],
       [1521, 1412, 3408,  949],
       [1561, 1500, 2432, 1197]])

Произведение заданной матрицы на единичную равно исходной матрице:

In [38]:
E = np.matrix('1 0 0 0; 0 1 0 0; 0 0 1 0; 0 0 0 1')
E.dot(A)

matrix([[26, 18, 10, 18],
        [10, 13, 14, 12],
        [ 5, 13,  6, 11],
        [18, 16, 44, 10]])

In [39]:
A.dot(E)

matrix([[26, 18, 10, 18],
        [10, 13, 14, 12],
        [ 5, 13,  6, 11],
        [18, 16, 44, 10]])

Произведение заданной матрицы на нулевую матрицу равно нулевой матрице:

In [40]:
Z = np.matrix('0 0 0 0; 0 0 0 0; 0 0 0 0; 0 0 0 0')
Z.dot(A)

matrix([[0, 0, 0, 0],
        [0, 0, 0, 0],
        [0, 0, 0, 0],
        [0, 0, 0, 0]])

In [41]:
A.dot(Z)

matrix([[0, 0, 0, 0],
        [0, 0, 0, 0],
        [0, 0, 0, 0],
        [0, 0, 0, 0]])

Определитель матрицы

In [42]:
np.linalg.det(A)

12272.000000000013

Определитель матрицы остается неизменным при ее транспонировании:

In [43]:
round(np.linalg.det(A), 3)

12272.0

In [44]:
round(np.linalg.det(A.T), 3)

12272.0

Если у матрицы есть строка или столбец, состоящие из нулей, то определитель
такой матрицы равен нулю:

In [45]:
N = np.matrix('3 2 3; 0 0 0; 12 4 5')
np.linalg.det(N)

0.0

При перестановке строк матрицы знак ее определителя меняется на
противоположный:

In [46]:
N = np.matrix('3 2 3; 5 6 9; 12 4 5')
round(np.linalg.det(N), 3)

-8.0

In [47]:
N = np.matrix('5 6 9; 3 2 3; 12 4 5')
round(np.linalg.det(N), 3)

8.0

Если у матрицы есть две одинаковые строки, то ее определитель равен нулю:

In [48]:
N = np.matrix('3 2 3; 3 2 3; 12 4 5')
np.linalg.det(N)

0.0

Если все элементы строки или столбца матрицы умножить на какое-то число, то и
определитель будет умножен на это число:

In [49]:
N = np.matrix('3 5 3; 3 2 3; 12 4 5')
k = 2
M = N.copy()
M[2, :] = k * M[2, :]
print(M)

[[ 3  5  3]
 [ 3  2  3]
 [24  8 10]]


In [50]:
det_N = round(np.linalg.det(N), 3)
det_M = round(np.linalg.det(M), 3)

In [51]:
det_N * k

126.0

In [52]:
det_M

126.0

Если все элементы строки или столбца можно представить как сумму двух
слагаемых, то определитель такой матрицы равен сумме определителей двух соответствующих
матриц:

In [53]:
C = A.copy()
C[1, :] += B[1, :]
print(C)

[[26 18 10 18]
 [12 17 17 24]
 [ 5 13  6 11]
 [18 16 44 10]]


In [54]:
A

array([[26, 18, 10, 18],
       [10, 13, 14, 12],
       [ 5, 13,  6, 11],
       [18, 16, 44, 10]])

In [55]:
B

array([[12, 18, 19, 14],
       [ 2,  4,  3, 12],
       [ 4,  5,  7, 74],
       [20, 21, 15, 42]])

In [56]:
round(np.linalg.det(C), 3)

89120.0

In [57]:
round(np.linalg.det(A), 3) + round(np.linalg.det(B), 3)

30128.0

Если к элементам одной строки прибавить элементы другой строки, умноженные на
одно и тоже число, то определитель матрицы не изменится:

In [58]:
C = A.copy()
C[1, :] = C[1, :] + 2 * C[0, :]
A

array([[26, 18, 10, 18],
       [10, 13, 14, 12],
       [ 5, 13,  6, 11],
       [18, 16, 44, 10]])

In [59]:
C

array([[26, 18, 10, 18],
       [62, 49, 34, 48],
       [ 5, 13,  6, 11],
       [18, 16, 44, 10]])

In [60]:
round(np.linalg.det(A), 3)

12272.0

In [61]:
round(np.linalg.det(C), 3)

12272.0

Если строка или столбец матрицы является линейной комбинацией других строк
(столбцов), то определитель такой матрицы равен нулю:

In [62]:
A[1, :] = A[0, :] + 2 * A[2, :]
round(np.linalg.det(A), 3)

-0.0

Если матрица содержит пропорциональные строки, то ее определитель равен нулю:

In [63]:
A[1, :] = 2 * A[0, :]
A

array([[26, 18, 10, 18],
       [52, 36, 20, 36],
       [ 5, 13,  6, 11],
       [18, 16, 44, 10]])

In [64]:
round(np.linalg.det(A), 3)

0.0

Обратная матрица

Обратная матрица обратной матрицы есть исходная матрица:

In [65]:
N = np.matrix('6 2; -7 12')
np.linalg.inv(N)

matrix([[ 0.13953488, -0.02325581],
        [ 0.08139535,  0.06976744]])

Обратная матрица транспонированной матрицы равна транспонированной матрице
от обратной матрицы:

In [66]:
np.linalg.inv(N.T)

matrix([[ 0.13953488,  0.08139535],
        [-0.02325581,  0.06976744]])

In [67]:
(np.linalg.inv(N)).T

matrix([[ 0.13953488,  0.08139535],
        [-0.02325581,  0.06976744]])

Обратная матрица произведения матриц равна произведению обратных матриц:

In [68]:
M = np.matrix('7. 2.; 6. 12.')
N = np.matrix('-1. 9.; 7. -8.')
np.linalg.inv(M.dot(N))

matrix([[ 0.01060606,  0.01186869],
        [ 0.01969697, -0.00176768]])

In [69]:
np.linalg.inv(N).dot(np.linalg.inv(M))

matrix([[ 0.01060606,  0.01186869],
        [ 0.01969697, -0.00176768]])

## Матричный метод

Рассмотрим систему линейных уравнений:
* x-2y+3z-t=6
* 2x+3y-4z+4t=-7
* 3x+y-2z-2t=9
* x-3y+7z+6t=-7

Создадим матрицу

In [70]:
K = np.array([[1., -2., 3., -1.], [2., 3., -4., 4.], [3., 1., -2., -2.], [1., -3., 7., 6.]])
K

array([[ 1., -2.,  3., -1.],
       [ 2.,  3., -4.,  4.],
       [ 3.,  1., -2., -2.],
       [ 1., -3.,  7.,  6.]])

Создадим вектор (правую часть системы)

In [71]:
L = np.array([[6.], [-7.], [9.], [-7.]])
L

array([[ 6.],
       [-7.],
       [ 9.],
       [-7.]])

Для решения системы воспользуемся функцией numpy.linalg.solve

In [72]:
np.linalg.solve(K, L)

array([[ 2.],
       [-1.],
       [ 0.],
       [-2.]])

## Метод Крамера

Найти решение СЛАУ при помощи метода Крамера.
* x-2y+3z-t=6
* 2x+3y-4z+4t=-7
* 3x+y-2z-2t=9
* x-3y+7z+6t=-7


Вычисляем определитель матрицы системы:

In [73]:
K = np.array([[1., -2., 3., -1.], [2., 3., -4., 4.], [3., 1., -2., -2.], [1., -3., 7., 6.]])
L = np.array([[6.], [-7.], [9.], [-7.]])

In [74]:
D = round(np.linalg.det(K), 3)
D

35.0

In [75]:
J = np.array([[6., -2., 3., -1.], [-7., 3., -4., 4.], [9., 1., -2., -2.], [-7., -3., 7., 6.]])

In [76]:
D_1 = round(np.linalg.det(J), 3)
D_1

70.0

In [77]:
J = np.array([[1., 6., 3., -1.], [2., -7., -4., 4.], [3., 9., -2., -2.], [1., -7., 7., 6.]])

In [78]:
D_2 = round(np.linalg.det(J), 3)
D_2

-35.0

In [79]:
J = np.array([[1., -2., 6., -1.], [2., 3., -7., 4.], [3., 1., 9., -2.], [1., -3., -7., 6.]])

In [80]:
D_3 = round(np.linalg.det(J), 3)
D_3

0.0

In [81]:
J = np.array([[1., -2., 3., 6.], [2., 3., -4., -7.], [3., 1., -2., 9.], [1., -3., 7., -7.]])

In [82]:
D_4 = round(np.linalg.det(J), 3)
D_4

-70.0

In [83]:
print(
    f" x = {D_1/D}"
    f" y = {D_2/D}"
    f" z = {D_3/D}" 
    f" t = {D_4/D}" 
     )

 x = 2.0 y = -1.0 z = 0.0 t = -2.0
